### ISSUE TITLE
OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by RaviH** [spencergibb/battleschool#26]
Mac OSX: 10.10.2
Python: 2.7.6
Ansible: 1.8.4

```
## Executing playbook /Users/rhasija/Library/Caches/battleschool/osx/sublime2.yml ################################ 
Task OK: setup

Task FAILED: mac_pkg Traceback (most recent call last):

  File "/Users/rhasija/.ansible/tmp/ansible-tmp-1428420410.62-215587963418155/mac_pkg", line 2184, in <module>

    main()

  File "/Users/rhasija/.ansible/tmp/ansible-tmp-1428420410.62-215587963418155/mac_pkg", line 579, in main

    installer.install(acquire_only)

  File "/Users/rhasija/.ansible/tmp/ansible-tmp-1428420410.62-215587963418155/mac_pkg", line 492, in install

    failed = pkg.install(archive.pkg_path())

  File "/Users/rhasija/.ansible/tmp/ansible-tmp-1428420410.62-215587963418155/mac_pkg", line 413, in install

    shutil.copytree(pkg_path, self._app_creates, symlinks=True)

  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 171, in copytree

    names = os.listdir(src)

OSError: [Errno 2] No such file or directory: '/Volumes/Sublime Text 2/Sublime Text'



Failed playbook: /Users/rhasija/Library/Caches/battleschool/osx/sublime2.yml

           to retry, use: --limit @/Users/rhasija/sublime2.retry



Playbook FAILED, ok=1, changed=0, unreachable=0, failed=1

kapasdevmac12fm:ansible-osx rhasija$ 



kapasdevmac12fm:ansible-osx rhasija$ ls /Volumes/Sublime\ Text

Applications	Sublime Text.app


kapasdevmac12fm:ansible-osx rhasija$ 
```

**Comment by spencergibb** [comment]
The error says `/Volumes/Sublime Text 2/Sublime Text` doesn't exist which is correct, it should be `/Volumes/Sublime Text 2/Sublime Text.app`.   Looks like the sublime yml files are missing that.

**Comment by RaviH** [comment]
Ok, I am a little confused. I have used this before and it worked. Does
different MAC OS could be causing directory structure to be different?

Sincerely,
Ravi Hasija.

http://javawithravi.com
Cell: 321-961-0536

**Comment by spencergibb** [comment]
not sure

**Comment by RaviH** [comment]
Here's the issue I think:

I am comparing my new laptop vs my old laptop. It seems like battle is
trying to install into
`/Volumes/Sublime Text 2/` in the new laptop whereas in the old laptop it
installed to `/Volumes/Macintosh HD/Applications/Sublime Text 2.app`

Sincerely,
Ravi Hasija.

http://javawithravi.com
Cell: 321-961-0536

**Comment by spencergibb** [comment]
Is this still an issue?
